version: '3.3'
services:
  db:
    container_name: minitwit_db
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes: 
      - db:/var/lib/postgresql/data
      
  server:
      container_name: minitwit
      image: ${DOCKER_USERNAME}/minitwitimage
      ports:
        - "8080:8080"
      restart: always
      links:
        - db:database
      depends_on:
        - db
        - grafana
        - prometheus
        
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana:4.5.2
    container_name: grafana
    ports:
      - "3000:3000"

volumes:
    db:
      driver: local
    server:
      external: false