setup.kibana.host: "127.0.0.1:5601"

filebeat.inputs:
- type: container
  paths: 
    - '/var/lib/docker/containers/*/*.log'

processors:
- add_docker_metadata:
    host: "unix:///var/run/docker.sock"

- decode_json_fields:
    fields: ["message"]
    target: "json"
    overwrite_keys: true

output.elasticsearch:
  hosts: ["elasticsearch:9200"]
  indices:
    - index: "filebeat-elastic-%{[agent.version]}-%{+yyyy.MM.dd}"
      when.or:
        - equals:
            container.name: "filebeat"
        - equals:
            container.name: "elasticsearch"
        - equals:
            container.name: "kibana"
    
    - index: "filebeat-minitwit-%{[agent.version]}-%{+yyyy.MM.dd}"
      when.or:
        - equals:
            container.name: "minitwit"

    - index: "filebeat-nginx-%{[agent.version]}-%{+yyyy.MM.dd}"
      when.or:
        - equals:
            container.name: "nginx"

logging.json: true
logging.metrics.enabled: false