on: 
  push:
    branches:
      - main
      - dev
  pull_request:
    types: [opened, reopened]
    branches:
      - main
      - testPipeline
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
        type: choice
        options:
        - info
        - warning
        - debug
      tags:
        description: 'Test scenario tags'
        required: false
        type: boolean
      environment:
        description: 'Environment to run tests against'
        type: environment
        required: true

name: Test

jobs:
  tests:
    runs-on: ubuntu-latest  
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: build and run
        run: | 
          docker-compose -f docker-compose-test.yml up -d
          docker-compose -f docker-compose-test.yml run test python3 minitwit_tests.py