on: 
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
        type: choice
        options:
        - info
        - warning
        - debug
      tags:
        description: 'Test scenario tags'
        required: false
        type: boolean
      environment:
        description: 'Environment to run tests against'
        type: environment
        required: true

name: Test

jobs:
  tests:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push tests
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile-minitwittests
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/test:latest

      - name: Run tests
        run: docker run ${{ secrets.DOCKER_USERNAME }}/test
        
        
      - name: Do we run this
        run: echo "Hello this is running"
  
      
